---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: primary
  region: eu-central-1
  version: "1.21"
managedNodeGroups:
  - instanceType: m5.large
    amiFamily: AmazonLinux2
    name: primary
    desiredCapacity: 2
    minSize: 2
    maxSize: 4